#initial Pose

initial_x: 0.0
initial_y: 0
initial_a: 0


# Path to  landmarks map file
path_land_map: /home/diego/kk/Tesis/yolo/catkin_ws/src/kalman_loc_qr/data/landmarks_casakmuybueno.txt

# Distance (in meters) to run EKF algorithm 
dist_update: 0.1

# Angle (in radians) to run EKF algorithm
angle_update: 0.3490658503

# Alpha parameters for sample_motion_model_odometry
alpha1: 0.01
alpha2: 0.02
alpha3: 0.03
alpha4: 0.04

# Mtrix Q for prediction step
q_matrix: [0.8, 0,    0,    
           0,    0.8, 0,    
           0,    0,    0.8 ]

# Mtrix Q for update step
r_matrix: [0.8, 0,    0,    
           0,    0.8, 0,    
           0,    0,    0.8 ]



